name: Pull requests

on:
  merge_group:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Build image and run tests
        shell: sh
        run: |
          set -e
          docker build . -t test
          ./tests/e2e/index.sh

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs:
      - run-checks
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Merge
        run: gh pr merge ${{ steps.extract-ref.outputs.ref }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Renovate conflicts
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run Renovate

  push-tag:
    name: Push tag
    runs-on: ubuntu-latest
    needs:
      - merge
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${{ github.event.repository.default_branch }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}
          fetch-depth: 0

      - name: Bump version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  tag-pushed:
    name: Tag pushed
    needs:
      - push-tag
    uses: ./.github/workflows/tags.yaml
